### PR TITLE
Fix unnamed workflow on pull request

### PR DESCRIPTION
**Pull request by dbalcomb**
This attempts to fix the issue where the check run appears under *(Unnamed workflow)* in the actions tab when triggered by a pull request.

Examples of this can be found on the following repositories:

* [actix/actix](https://github.com/actix/actix/actions/runs/57722049)
* [bastion-rs/bastion](https://github.com/bastion-rs/bastion/actions)
* [tokio-rs/tracing](https://github.com/tokio-rs/tracing/actions)

It appears that the reason is due to the pull request workflow running on a short-lived merge commit. When the UI tries to display the workflow it shows as *(Unknown event)* and *(Unnamed workflow)* because it cannot find any reference to the commit SHA.

Fortunately the context payload includes the pull request information so this simply changes the check to use the pull request head SHA when available.

I have successfully tested this on a pull request workflow but it might need some further testing. Specifically according to the [event types & payloads](https://developer.github.com/v3/activity/events/types/) documentation there are *pull request review* and *pull request review comment* events which also include the pull request in the payload. According to the [events that trigger workflows](https://help.github.com/en/actions/reference/events-that-trigger-workflows) they also use a merge commit. I suppose that it cannot hurt as if there is no merge commit then the default SHA will be the same as the pull request head SHA.

This may also be related to #45.

### CODE REVIEW

**Comment by fbecart** [comment]
My project is having the same issue https://github.com/fbecart/zinoma/actions
Of course it's not blocking, but a fix would be welcome.

@dbalcomb Can I help testing this PR? If so, could you give me some indication how to proceed?

**Comment by dbalcomb** [comment]
@fbecart After some further thought I don't think that additional testing is necessary but it would be good to get input from the developer of the action.

@svartalf Could you take a look at this? I see that you are working on the [actions-rs/clippy](https://github.com/actions-rs/clippy) action as a replacement for this one. I am not entirely sure how it differs but it would be good to see this fix landed in the meantime. Assuming that you approve of course.

**Comment by svartalf** [comment]
Hey, @dbalcomb! Sorry for not getting back to you earlier.

In a current state `actions-rs/clippy` is nothing more than an experiment; I wanted to check if it would be possible right not do the same what this Action does, but without requiring `GITHUB_TOKEN` and communicating with GH API.
It's kinda possible by abusing undocumented things, but whole approach is very ugly overall, so it's not like this Action will be deprecated soon and your fix is definitely an amazing finding!

It looks fine for me, so I'll merge and publish it tomorrow. Thank you for debugging this thing :)

**Comment by pitkley** [comment]
I quickly wanted to mention that I tested this PR and can confirm that the annotations are now associated with the correct check for pull-requests. :+1:

**Comment by svartalf** [comment]
This fix was published in `v1.0.7` and can be used now as latest `actions-rs/clippy-check@v1` tag.

**Pull request merged**
